# Generated by Django 4.2.3 on 2023-09-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=30, unique=True)),
                ("role", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="user2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=30, null=True)),
                ("email", models.CharField(max_length=30, null=True)),
                ("password", models.CharField(max_length=30, null=True)),
                ("cpassword", models.CharField(max_length=30, null=True)),
                (
                    "login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fddonationapp.log",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=30, null=True)),
                ("email", models.CharField(max_length=30, null=True)),
                ("password", models.CharField(max_length=30, null=True)),
                ("cpassword", models.CharField(max_length=30, null=True)),
                (
                    "login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fddonationapp.log",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foodname", models.CharField(max_length=30, null=True)),
                ("foodtype", models.CharField(max_length=30, null=True)),
                ("quantity", models.CharField(max_length=30, null=True)),
                ("cookingtime", models.CharField(max_length=30, null=True)),
                ("image", models.FileField(max_length=30, null=True, upload_to="")),
                ("address", models.CharField(max_length=30, null=True)),
                ("phone", models.CharField(max_length=30, null=True)),
                (
                    "donarid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fddonationapp.user",
                    ),
                ),
            ],
        ),
    ]
