# Generated by Django 4.2.3 on 2023-10-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fddonationapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.CreateModel(
            name="accepting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receivername", models.CharField(max_length=30, null=True)),
                ("donarname", models.CharField(max_length=30, null=True)),
                ("foodname", models.CharField(max_length=30, null=True)),
                ("foodtype", models.CharField(max_length=30, null=True)),
                ("cookingtime", models.CharField(max_length=30, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("address", models.CharField(max_length=30, null=True)),
                ("phone", models.CharField(max_length=30, null=True)),
                ("bookingdate", models.CharField(max_length=30, null=True)),
                ("bookingstatus", models.CharField(max_length=120, null=True)),
                (
                    "donarid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fddonationapp.user",
                    ),
                ),
                (
                    "foodid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fddonationapp.food",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fddonationapp.user2",
                    ),
                ),
            ],
        ),
    ]
