# Generated by Django 4.2.3 on 2023-10-13 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fddonationapp", "0002_alter_food_image_accepting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accepting",
            old_name="bookingdate",
            new_name="acceptingdate",
        ),
        migrations.RenameField(
            model_name="accepting",
            old_name="bookingstatus",
            new_name="acceptingstatus",
        ),
    ]
