# Generated by Django 4.2.3 on 2023-10-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fddonationapp", "0004_rename_userid_accepting_receiverid"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="acceptingstatus",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
