# Generated by Django 4.2.3 on 2023-10-30 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fddonationapp", "0005_food_acceptingstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="acceptingstatus",
            new_name="foodstatus",
        ),
    ]
