# Generated by Django 5.2.6 on 2025-10-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fddonationapp', '0006_rename_acceptingstatus_food_foodstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user2',
            new_name='donar',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='receiver',
        ),
    ]
